// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5mTaPUUZhPA8A3lDWfU6RvsA55Gm3_4Q',
    appId: '1:58471064886:web:b7bda487e3d28c4cc9ff97',
    messagingSenderId: '58471064886',
    projectId: 'villatrip-64bc3',
    authDomain: 'villatrip-64bc3.firebaseapp.com',
    storageBucket: 'villatrip-64bc3.firebasestorage.app',
    measurementId: 'G-HMXCNNHYNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0UwASXkINk5kRgN6Lo0PQNenoLpIh8yM',
    appId: '1:58471064886:android:5c44ce2f86f16d3dc9ff97',
    messagingSenderId: '58471064886',
    projectId: 'villatrip-64bc3',
    storageBucket: 'villatrip-64bc3.firebasestorage.app',
  );
}
